[package]
name = "embassy-release"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
walkdir = "2.5.0"
toml = "0.9.5"
toml_edit = { version = "0.23.1", features = ["serde"] }
serde = { version = "1.0.198", features = ["derive"] }
regex = "1.10.4"
anyhow = "1"
petgraph = "0.8.2"
semver = "1.0.26"
cargo-semver-checks = "0.43.0"
log = "0.4"
simple_logger = "5.0.0"
temp-file = "0.1.9"
flate2 = "1.1.1"

[patch.crates-io]
cargo-semver-checks = { path = "../../cargo-semver-checks" }
